version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src-plugin"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"

  - package-ecosystem: "bun"
    directory: "/src-client"
    schedule:
      interval: "daily"
