version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"


  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
