name: test
permissions: write-all
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "8.0.x"

            - name: Build
              run: dotnet build -c Release

            - name: Test
              run: dotnet test -c Release
