name: ci
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "8.0.x"

            - name: Setup NuGet
              uses: NuGet/setup-nuget@v1

            - name: Restore Packages
              run: dotnet restore
              working-directory: src-plugin

            - name: Build
              run: dotnet build -c Release
              working-directory: src-plugin

            - name: Test
              run: dotnet test -c Release
              working-directory: src-plugin
